# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

lane :setup do
  match(platform: "tvos", type: "development", app_identifier: "tv.brunstad.app", api_key_path: 'fastlane/api_key.json')
  match(platform: "tvos", type: "appstore", app_identifier: "tv.brunstad.app", api_key_path: 'fastlane/api_key.json')
end

platform :ios do

  desc "Push a new beta build to TestFlight"
  lane :beta do
    setup_ci
    match(platform: "tvos", type: "appstore", api_key_path: 'fastlane/api_key.json')
    sh("cd .. && ./scripts/build.sh pre")
    begin
      build_app(scheme: "BCC Media tvOS", cloned_source_packages_path: "./tmp/build", skip_profile_detection: true)
    ensure
      sh("cd .. && ./scripts/build.sh post")
    end
    upload_to_testflight(
      distribute_external: true,
      changelog: "See the betatester group on telegram.",
      api_key_path: 'fastlane/api_key.json',
      groups: [
        "Testers"
      ]
    )
  end

  lane :release do
    current_version_number = increment_version_number_in_xcodeproj(
      xcodeproj: "./BCC Media tvOS/BCC Media tvOS.xcodeproj",
    )
    current_build_number = increment_build_number_in_xcodeproj(
      xcodeproj: "./BCC Media tvOS/BCC Media tvOS.xcodeproj",
    )
    commit_version_bump(
      message: "chore(tvos): bump version to #{current_version_number}+#{current_build_number}",
      xcodeproj: "./BCC Media tvOS/BCC Media tvOS.xcodeproj",
    )
    tag = add_git_tag(
      grouping: "tvos",
      includes_lane: false,
      prefix: "v",
      build_number: current_version_number,
      postfix: "+"+current_build_number,
    )
    push_git_tags(
      tags: tag,
    )
  end
  
end
