name: deploy-tvos
on:
  workflow_dispatch:
  push:
    tags:
      - "tvos/v*"
jobs:
  build:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v2
      - name: List Xcode installations for debugging
        run: sudo ls -1 /Applications | grep "Xcode"
      - name: Select Xcode 16.3
        run: sudo xcode-select -s /Applications/Xcode_16.3.app/Contents/Developer
      - name: Put api key into .p8 file
        run: echo "${{ secrets.APPLE_STORE_API_KEY_RAW }}" > fastlane/api_key.p8
      - name: Put cert into .p12 file
        run: echo "${{ secrets.CERTIFICATE_BASE64 }}" | base64 -d > fastlane/certificate.p12
      - name: Run tests
        run: |
          xcrun simctl runtime list
          xcrun simctl create "Apple TV" "Apple TV"
          xcrun simctl boot "Apple TV"
          gem install xcpretty
          set -o pipefail && xcrun xcodebuild test \
            -workspace "./BCC Media.xcworkspace" \
            -scheme uitests \
            -destination 'platform=tvOS Simulator,name=Apple TV,OS=18.0' \
            -derivedDataPath './DerivedData' \
            LOGIN_API_KEY=${{ secrets.LOGIN_API_KEY }} \
            AUTOLOGIN_HOST=${{ vars.AUTOLOGIN_HOST }} \
            RUDDER_WRITE_KEY=${{ secrets.RUDDER_WRITE_KEY }} \
            RUDDER_DATAPLANE_URL=${{ secrets.RUDDER_DATAPLANE_URL }} \
            | xcpretty
      - name: Upload screenshots
        uses: actions/upload-artifact@v4
        with:
          name: tvOS-test-screenshots
          path: DerivedData/**/Logs/Test/*.xcresult
      - name: Run fastlane
        env:
          RUDDER_WRITE_KEY: ${{ secrets.RUDDER_WRITE_KEY }}
          RUDDER_DATAPLANE_URL: ${{ secrets.RUDDER_DATAPLANE_URL }}
          NPAW_ACCOUNT_CODE: ${{ secrets.NPAW_ACCOUNT_CODE }}
          UNLEASH_URL: ${{ vars.UNLEASH_URL }}
          UNLEASH_CLIENT_KEY: ${{ vars.UNLEASH_CLIENT_KEY }}
          SENTRY_DSN: ${{ vars.SENTRY_DSN }}
        run: |
          bundle install
          fastlane beta --verbose
